apiVersion: v1
kind: Service
metadata:
  name: pentaho-server-service
  labels:
    app: pentaho-server-service
spec:
  type: NodePort
  selector:
    app: pentaho-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentaho-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pentaho-server
  template:
    metadata:
      labels:
        app: pentaho-server
    spec:
      volumes:
        - name: key
          secret:
            secretName: key
        - name: pentaho-license
          secret:
            secretName: pentaho-license
        - name: init-databases-volume
          configMap:
            name: init-db-scripts
      containers:
      - name: postgres
        image: postgres:9.5
        imagePullPolicy: "Always"
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
            name: postgresql
            protocol: TCP
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
          - name: init-databases-volume
            mountPath: /docker-entrypoint-initdb.d
      - name: pentaho-server
        image: gcr.io/pentaho-support-team/pentaho/pentaho-server:9.1.0.7
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "4500Mi"
          requests:
            memory: "2000Mi"
        ports:
          - containerPort: 8080
        volumeMounts:
            - name: key
              mountPath: "/secrets/key"
            - name: pentaho-license
              mountPath: "/secrets/pentahoLicense"
        env:
            - name: GCS_PENTAHO_CONFIG_PATH
              value: "gs://support-emea-hv/pentaho-gke/psql12-config"
            - name: PENTAHO_INSTALLATION_PATH
              value: "/opt/pentaho/pentaho-server"
            - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
              value: "/secrets/key/key.json"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key/key.json"
            - name: PENTAHO_INSTALLED_LICENSE_PATH
              value: "/secrets/pentahoLicense/.installedLicenses.xml"
            - name: CATALINA_OPTS
              value: "-Dpentaho.installed.licenses.file=/secrets/pentahoLicense/.installedLicenses.xml -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:+UseCGroupMemoryLimitForHeap -Dfile.encoding=utf8 -XX:MaxRAMPercentage=80.0 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExitOnOutOfMemoryError -XX:+UseG1GC"                
        args: ["/opt/pentaho/pentaho-server/tomcat/bin/catalina.sh","run"]
        