---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: cd-jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
      name: ui
---