---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-agent
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: cd-jenkins
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30500
      name: slavelistener
---