--
-- These queries create OLTP logging tables for a PostgreSQL database
--
\connect hibernate hibuser

CREATE SCHEMA pentaho_dilogs;

-- Job log table
--

CREATE TABLE pentaho_dilogs.job_logs
(
  ID_JOB INTEGER
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, STARTDATE TIMESTAMP
, ENDDATE TIMESTAMP
, LOGDATE TIMESTAMP
, DEPDATE TIMESTAMP
, REPLAYDATE TIMESTAMP
, LOG_FIELD TEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, START_JOB_ENTRY VARCHAR(255)
, CLIENT VARCHAR(255)
)
;
CREATE INDEX IDX_job_logs_1 ON pentaho_dilogs.job_logs(ID_JOB)
;
CREATE INDEX IDX_job_logs_2 ON pentaho_dilogs.job_logs(ERRORS, STATUS, JOBNAME)
;


-- Job entry log table
--

CREATE TABLE pentaho_dilogs.jobentry_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, "RESULT" CHAR(5)
, NR_RESULT_ROWS BIGINT
, NR_RESULT_FILES BIGINT
, LOG_FIELD TEXT
, COPY_NR INTEGER
)
;
CREATE INDEX IDX_jobentry_logs_1 ON pentaho_dilogs.jobentry_logs(ID_BATCH)
;


-- Logging channel log table
--

CREATE TABLE pentaho_dilogs.channel_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, LOGGING_OBJECT_TYPE VARCHAR(255)
, OBJECT_NAME VARCHAR(255)
, OBJECT_COPY VARCHAR(255)
, REPOSITORY_DIRECTORY VARCHAR(255)
, FILENAME VARCHAR(255)
, OBJECT_ID VARCHAR(255)
, OBJECT_REVISION VARCHAR(255)
, PARENT_CHANNEL_ID VARCHAR(255)
, ROOT_CHANNEL_ID VARCHAR(255)
)
;
CREATE TABLE pentaho_dilogs.checkpoint_logs
(
  ID_JOB_RUN INTEGER
, ID_JOB INTEGER
, JOBNAME VARCHAR(255)
, NAMESPACE VARCHAR(255)
, CHECKPOINT_NAME VARCHAR(255)
, CHECKPOINT_COPYNR SMALLINT
, ATTEMPT_NR INTEGER
, JOB_RUN_START_DATE TIMESTAMP
, LOGDATE TIMESTAMP
, RESULT_XML TEXT
, PARAMETER_XML TEXT
)
;
CREATE INDEX IDX_checkpoint_logs_1 ON pentaho_dilogs.checkpoint_logs(ID_JOB_RUN)
;
CREATE INDEX IDX_checkpoint_logs_2 ON pentaho_dilogs.checkpoint_logs(JOBNAME, NAMESPACE)
;


-- Transformation log table
--

CREATE TABLE pentaho_dilogs.trans_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, TRANSNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, STARTDATE TIMESTAMP
, ENDDATE TIMESTAMP
, LOGDATE TIMESTAMP
, DEPDATE TIMESTAMP
, REPLAYDATE TIMESTAMP
, LOG_FIELD TEXT
, EXECUTING_SERVER VARCHAR(255)
, EXECUTING_USER VARCHAR(255)
, CLIENT VARCHAR(255)
)
;
CREATE INDEX IDX_trans_logs_1 ON pentaho_dilogs.trans_logs(ID_BATCH)
;
CREATE INDEX IDX_trans_logs_2 ON pentaho_dilogs.trans_logs(ERRORS, STATUS, TRANSNAME)
;


-- Step log table
--

CREATE TABLE pentaho_dilogs.step_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY SMALLINT
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, LOG_FIELD TEXT
)
;


-- Step performance log table
--

CREATE TABLE pentaho_dilogs.transperf_logs
(
  ID_BATCH INTEGER
, SEQ_NR INTEGER
, LOGDATE TIMESTAMP
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, STEP_COPY INTEGER
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, INPUT_BUFFER_ROWS BIGINT
, OUTPUT_BUFFER_ROWS BIGINT
)
;


-- Metrics log table
--

CREATE TABLE pentaho_dilogs.metrics_logs
(
  ID_BATCH INTEGER
, CHANNEL_ID VARCHAR(255)
, LOG_DATE TIMESTAMP
, METRICS_DATE TIMESTAMP
, METRICS_CODE VARCHAR(255)
, METRICS_DESCRIPTION VARCHAR(255)
, METRICS_SUBJECT VARCHAR(255)
, METRICS_TYPE VARCHAR(255)
, METRICS_VALUE BIGINT
)
;
