apiVersion: v1
kind: Service
metadata:
  name: carte-exp-service
  labels:
    app: carte-exp-service
spec:
  type: NodePort
  selector:
    app: carte-exp
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30280
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdi-gke-carte-exp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carte-exp
  template:
    metadata:
      labels:
        app: carte-exp
    spec:
      volumes:
        - name: key
          secret:
            secretName: key
        - name: pentaho-license
          secret:
            secretName: pentaho-license
      containers:
      - name: pdi-gke-carte-server
        image: gcr.io/pentaho-support-team/pentaho/carte4tray:8.3.0.0
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "2Gi"
        ports:
          - containerPort: 9080
        volumeMounts:
            - name: key
              mountPath: "/secrets/key"
            - name: pentaho-license
              mountPath: "/secrets/pentahoLicense"
        env:
            - name: GCOUD_PENTAHO_PROJECT_PATH
              value: "gs://support-emea-hv/demo-db/project-artifact.zip"
            - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
              value: "/secrets/key/key.json"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key/key.json"
            - name: PENTAHO_INSTALLED_LICENSE_PATH
              value: "/secrets/pentahoLicense/.installedLicenses.xml"
            - name: PENTAHO_DI_JAVA_OPTIONS
              value: "-Dfile.encoding=utf8 -XX:+ExitOnOutOfMemoryError -DKETTLE_MAX_LOGGING_REGISTRY_SIZE=0"  
              #value: "-XX:+UseContainerSupport -XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:G1ReservePercent=10"
        #command: ["./kitchen -file=$PENTAHO_PROJECT_PATH/generateLongLog.kjb"]  
        #command: ["bash"]
        #args: ["/opt/pentaho/data-integration/carte.sh", "/opt/pentaho/data-integration/pwd/carte-config-master-8080.xml"]  
        #args: ["/opt/pentaho/data-integration/carte.sh", "$CURRENT_HOSTNAME", "8080"]  
        #args: ["bash"]
        