apiVersion: v1
kind: Service
metadata:
  name: tray-service
  labels:
    app: tray
spec:
  type: NodePort
  selector:
    app: tray
  ports:
    - port: 9115
      targetPort: 9115
      nodePort: 30115
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tray-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tray
  template:
    metadata:
      labels:
        app: tray
    spec:
      volumes:
        - name: pentaho-es-license
          secret:
            secretName: pentaho-es-license
        - name: tray-config
          configMap:
            name: tray-config
      containers:
      - name: tray-gke-server
        image: gcr.io/pentaho-support-team/pentaho/tray-server:1.0.11-SNAPSHOT-2
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
          - containerPort: 9115
        readinessProbe:
          tcpSocket:
            port: 9115
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9115
          initialDelaySeconds: 15
          periodSeconds: 20 
        volumeMounts:
          - name: pentaho-es-license
            mountPath: "/secrets/pentaho-es-license"
          - name: tray-server-config
            mounthPath: /opt/pentaho/tray/conf
        env:
          - name: PENTAHO_ES_LICENSE_FILE
            value: "/secrets/pentaho-es-license/es-license-key.txt" 
        #command: ["./kitchen -file=$PENTAHO_PROJECT_PATH/generateLongLog.kjb"]  
        #command: ["bash"]
        #args: ["/opt/pentaho/data-integration/carte.sh", "/opt/pentaho/data-integration/pwd/carte-config-master-8080.xml"]  
        #args: ["/opt/pentaho/data-integration/carte.sh", "$CURRENT_HOSTNAME", "8080"]  
        #args: ["bash"]
        